config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here

  resources :dynamic_bmsm_groups

  resources :dynamic_bmsm_tiers
  namespace :admin do
    resources :dynamic_bmsm_groups do
      member do
        get 'users'
        put 'update_user_group'
      end
    end

    resources :dynamic_bmsm_tiers
  end


end

app/models/spree/dynamic_bmsm_group.rb
class Spree::DynamicBmsmGroup < ActiveRecord::Base
  attr_accessible :name, :description, :number
  has_many :dynamic_bmsm_tiers
  has_many :spree_users, :class_name => "Spree::User"
  validates :number, :presence => true, :uniqueness => true
end

app/controllers/spree/admin/dynamic_bmsm_groups_controller.rb
class Spree::Admin::DynamicBmsmGroupsController < Spree::Admin::BaseController
  before_filter :set_spree_dynamic_bmsm_group, :only => [:edit, :update, :destroy]

  def index
    @spree_dynamic_bmsm_groups = Spree::DynamicBmsmGroup.all
  end

  def new
    @spree_dynamic_bmsm_group = Spree::DynamicBmsmGroup.new
  end

  def edit
    @spree_dynamic_bmsm_group = Spree::DynamicBmsmGroup.find(params[:id])
  end

  def create
    @spree_dynamic_bmsm_group = Spree::DynamicBmsmGroup.new(spree_dynamic_bmsm_group_params)
    if @spree_dynamic_bmsm_group.save
      redirect_to admin_dynamic_bmsm_groups_path, :notice => 'Group was successfully created.'
    else
      render :action => 'new'
    end
  end

  def update
    if @spree_dynamic_bmsm_group.update_attributes(spree_dynamic_bmsm_group_params)
      redirect_to admin_dynamic_bmsm_groups_path, :notice => 'Group was successfully updated.'
    else
      render :action => 'edit'
    end
  end

  def users
    @group = Spree::DynamicBmsmGroup.find(params[:id])
    @users = @group.spree_users
  end

  def update_user_group
    user = Spree::User.find(params[:user][:id])
    group = Spree::DynamicBmsmGroup.find(params[:user][:dynamic_bmsm_group_id])
    user.update_attribute(:dynamic_bmsm_group_id, group.id)
    redirect_to users_admin_dynamic_bmsm_group_path(group), :notice => "#{user.email} assigned to #{group.name}."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_spree_dynamic_bmsm_group
    @spree_dynamic_bmsm_group = Spree::DynamicBmsmGroup.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def spree_dynamic_bmsm_group_params
    #params.require(:dynamic_bmsm_group).permit(:name, :description)
    params[:dynamic_bmsm_group]
  end
end

app/views/spree/admin/dynamic_bmsm_groups/_form.html.erb
<%= render "spree/shared/error_messages", :target => @spree_dynamic_bmsm_group %>

<%= form_for [spree, :admin, @spree_dynamic_bmsm_group] do |f| %>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.select :number, [nil, 1,2,3,4] %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spree/admin/dynamic_bmsm_groups/_user_form.html.erb
<%= form_for user, :url => update_user_group_admin_dynamic_bmsm_group_path(group)  do |f| %>
    <%= f.hidden_field :id %>
    <%= f.collection_select :dynamic_bmsm_group_id,
                            Spree::DynamicBmsmGroup.all,
                            :id,
                            :name,
                            :prompt => true
    %>
   <%= f.submit %>
<% end %>

app/views/spree/admin/dynamic_bmsm_groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Cancel', admin_dynamic_bmsm_groups_path %>

app/views/spree/admin/dynamic_bmsm_groups/index.html.erb
<h1>DBMSM Groups</h1>
<%= link_to 'Create Group', new_admin_dynamic_bmsm_group_path %>
|
<%= link_to 'Manage Tiers', admin_dynamic_bmsm_tiers_path %>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spree_dynamic_bmsm_groups.each do |dynamic_bmsm_group| %>
      <tr>
        <td><%= dynamic_bmsm_group.number %></td>
        <td><%= dynamic_bmsm_group.name %></td>
        <td><%= dynamic_bmsm_group.description %></td>
        <td>
          <%= link_to 'Users', users_admin_dynamic_bmsm_group_path(dynamic_bmsm_group) %>
          |
          <%= link_to 'Edit', edit_admin_dynamic_bmsm_group_path(dynamic_bmsm_group) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/dynamic_bmsm_groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Cancel', admin_dynamic_bmsm_groups_path %>

app/views/spree/admin/dynamic_bmsm_groups/users.html.erb
<h1>User for <%= @group.name %></h1>
<%= link_to 'Back to Groups', admin_dynamic_bmsm_groups_path %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td class="field"><%= render 'user_form', :user => user, :group => @group %></td>
      </tr>
    <% end %>
  </tbody>
</table>