config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here

  resources :dynamic_bmsm_groups

  resources :dynamic_bmsm_tiers
  namespace :admin do
    resources :dynamic_bmsm_groups do
      member do
        get 'users'
        put 'update_user_group'
      end
    end

    resources :dynamic_bmsm_tiers
  end


end

app/models/spree/dynamic_bmsm_tier.rb
class Spree::DynamicBmsmTier < ActiveRecord::Base
  attr_accessible :dynamic_bmsm_group_id, :label, :level, :discount
  belongs_to :dynamic_bmsm_group

  validates :dynamic_bmsm_group_id, :label, :level, :discount, :presence => true
end

app/controllers/spree/admin/dynamic_bmsm_tiers_controller.rb
class Spree::Admin::DynamicBmsmTiersController < Spree::Admin::BaseController
  before_filter :set_dynamic_bmsm_tier, :only => [:edit, :update, :destroy]

  def index
    group_id = params[:group_id]
    if group_id.present? && group_id.to_i >0
      @spree_dynamic_bmsm_tiers = Spree::DynamicBmsmTier.where(:dynamic_bmsm_group_id => group_id.to_i)
    else
      @spree_dynamic_bmsm_tiers = Spree::DynamicBmsmTier.all
    end
  end

  def new
    @spree_dynamic_bmsm_tier = Spree::DynamicBmsmTier.new
  end

  def edit
    @spree_dynamic_bmsm_tier = Spree::DynamicBmsmTier.find(params[:id])
  end

  def create
    @spree_dynamic_bmsm_tier = Spree::DynamicBmsmTier.new(spree_dynamic_bmsm_tier_params)
    if @spree_dynamic_bmsm_tier.save
      redirect_to admin_dynamic_bmsm_tiers_path, :notice => 'Tier was successfully created.'
    else
      render :action => 'new'
    end
  end

  def update
    if @spree_dynamic_bmsm_tier.update_attributes(spree_dynamic_bmsm_tier_params)
      redirect_to admin_dynamic_bmsm_tiers_path, notice: 'Tier was successfully updated.'
    else
      render :action => 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dynamic_bmsm_tier
      @spree_dynamic_bmsm_tier = Spree::DynamicBmsmTier.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def spree_dynamic_bmsm_tier_params
      #params.require(:dynamic_bmsm_tier).permit(:dynamic_bmsm_groups, :label, :level, :discount)
      params[:dynamic_bmsm_tier]
    end
end

app/views/spree/admin/dynamic_bmsm_tiers/_form.html.erb
<%= render "spree/shared/error_messages", :target => @spree_dynamic_bmsm_tier %>

<%= form_for [:admin, @spree_dynamic_bmsm_tier] do |f| %>
  <div class="field">
    <%= f.label :bmsm_groups %><br>
    <%= f.collection_select :dynamic_bmsm_group_id,
                            Spree::DynamicBmsmGroup.all,
                            :id,
                            :number,
                            :prompt => true
    %>
  </div>
  <div class="field">
    <%= f.label :label, "Internal Label" %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :level, "Order Total Threshold" %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :discount, "Discount %" %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spree/admin/dynamic_bmsm_tiers/edit.html.erb
<h1>Editing DBMSM Tier</h1>

<%= render 'form' %>

<%= link_to 'Cancel', admin_dynamic_bmsm_tiers_path %>

app/views/spree/admin/dynamic_bmsm_tiers/index.html.erb
<h1>DBMSM Tiers</h1>

<%= link_to 'Create New Tier', new_admin_dynamic_bmsm_tier_path %>
|
<%= link_to 'Manage Groups', admin_dynamic_bmsm_groups_path %>

<table>
  <thead>
    <tr>
      <th>Group #</th>
      <th>Internal Label</th>
      <th>Order Total Threshold</th>
      <th>Discount %</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spree_dynamic_bmsm_tiers.each do |dynamic_bmsm_tier| %>
      <tr>
        <td><%= dynamic_bmsm_tier.dynamic_bmsm_group.number %></td>
        <td><%= dynamic_bmsm_tier.label %></td>
        <td><%= number_to_currency(dynamic_bmsm_tier.level) %></td>
        <td><%= dynamic_bmsm_tier.discount %>%</td>
        <td>
          <%= link_to 'Edit', edit_admin_dynamic_bmsm_tier_path(dynamic_bmsm_tier) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/dynamic_bmsm_tiers/new.html.erb
<h1>New DBMSM Tier</h1>

<%= render 'form' %>

<%= link_to 'Cancel', admin_dynamic_bmsm_tiers_path %>